before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: rabbitmq_exporter-{{.Version}}.{{.Target}}
    targets:
    - linux_amd64
    - linux_arm64
    - linux_arm_6
    - linux_arm_7
    - windows_amd64
    - darwin_amd64
    - darwin_arm64
    tags: netgo staticbuild
    ldflags: 
      -  -X main.Version={{.Version}}
      -  -X main.Revision={{.ShortCommit}}
      -  -X main.Branch={{.Branch}}
      -  -X main.BuildDate={{.CommitDate}}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  discussion_category_name: Announcements