name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: go tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: run tests
      run: |
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOPATH/bin
        go tests ./... -v
